version: "3.8"

services:
  web:
    container_name: web
    image: akwanmaroso/deals-test_web
    ports:
      - "5001:5001"
    environment:
      PORT: "5001"
      config: "docker"
    depends_on:
      - mongodb
      - redis
    restart: always
    networks:
      - networkapi
  redis:
    image: redis:6.0.9-alpine
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - networkapi

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - mongodbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: S3cret1234
    networks:
      - networkapi

volumes:
  mongodbdata:

networks:
  networkapi:
    driver: bridge
