version: "3.8"

services:
  web:
    container_name: users-api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "5001:5001"
    environment:
      PORT: "5001"
      config: "docker"
    depends_on:
      - mongo_db
      - redis
    restart: always
    # volumes:
    #   - users-api-data:/app
    networks:
      - web_api
  redis:
    image: redis:6.0.9-alpine
    container_name: api_redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web_api

  mongo_db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: S3cret1234
    networks:
      - web_api

volumes:
  mongodb-data:
  users-api-data:

networks:
  web_api:
    driver: bridge
