apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    io.kompose.service: web
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: web
  template:
    metadata:
      labels:
        io.kompose.network/networkapi: "true"
        io.kompose.service: web
    spec:
      containers:
        - name: web
          image: akwanmaroso/deals-test_web
          ports:
            - containerPort: 5001
          env:
            - name: PORT
              value: "5001"
            - name: config
              value: docker
      restartPolicy: Always
