server:
  AppVersion: 1.0.0
  Port: :5001
  PprofPort: :5555
  Mode: Development
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: true
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: false

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

redis:
  RedisAddr: localhost:6379
  RedisPassword:
  RedisDb: 0
  RedisDefaultdb: 0
  MinIdleConns: 200
  PoolSize: 12000
  PoolTimeout: 240
  Password: ""
  DB: 0

jwt: 
  AccessSecret: supersecretaccesstoken
  RefreshSecret: supersecretrefreshtoken

mongodb:
  URI: mongodb://root:S3cret1234@localhost:27017
